command: [
  "uvicorn",
  "src.app:app",
  "--host", "0.0.0.0",
  "--port", "8000"
]

env:
  - name: 'PORT'
    value: "8000"
  - name: 'HOST'
    value: "0.0.0.0"
  - name: 'ENVIRONMENT'
    value: "production"

